In [1]:
import numpy as np

S = np.array([
    [2, 0],
    [0, 2]
])

v = np.array([
    [2],
    [3]
])

result = S @ v

print(result)

[[4]
 [6]]


- Try changing the scaling factor to 0.5 or 3 and observe the result.

In [2]:
import numpy as np

S = np.array([
    [2, 0],
    [0, 2]
])

v = np.array([
    [0.5],
    [3]
])

result = S @ v

print(result)

[[1.]
 [6.]]


In [3]:
import numpy as np

S = np.array([
    [2, 0],
    [0, 2]
])

v = np.array([
    [3],
    [0.5]
])

result = S @ v

print(result)

[[6.]
 [1.]]


### Mini Experiment

In [4]:
import numpy as np

v = np.array([[1], [2]])

S = np.array([
    [3, 0],
    [0, 3]
])

print(S @ v)

[[3]
 [6]]


**Questions:**

### What happened to the vector?
- Vector magnitude has changed.

### Did its direction change?
- No. it's direction is remain unchanged.

### Did its magnitude change?
- Yes, its magnitude has increased.