# Day 28 — Linear Algebra Capstone Project
### Project Goal

Analyze a small dataset using the linear algebra concepts you've learned:

- Vectors
- Vector magnitude
- Dot product
- Matrices
- Matrix multiplication
- Matrix transformations
- Eigenvector intuition

### Task 1 — Load the Dataset

In [1]:
import pandas as pd

df = pd.read_csv("dataset.csv")

print(df)

   Student  Math  Science  English
0    Alice    85       90       78
1      Bob    70       65       80
2  Charlie    92       88       91
3    David    60       72       68
4     Emma    95       94       96


### Task 2 — Convert to a Matrix

Extract only the numeric columns.

In [2]:
import numpy as np

X = df[["Math", "Science", "English"]].to_numpy()

print(X)
print(X.shape)

[[85 90 78]
 [70 65 80]
 [92 88 91]
 [60 72 68]
 [95 94 96]]
(5, 3)


**Questions:**

- How many rows?
- How many columns?
- What does each row represent?
- What does each column represent?

In [4]:
print(f'Number of rows in the dataset: {df.shape[0]}')
print(f'Number of columns in the dataset: {df.shape[1]}')

Number of rows in the dataset: 5
Number of columns in the dataset: 4


### Task 3 — Vector Magnitude

Calculate the magnitude of each student's score vector.

In [5]:
magnitudes = np.linalg.norm(X, axis=1)

print(magnitudes)

[146.31814652 124.59935794 156.48961627 115.79291861 164.55090398]


Interpretation:

- Which student has the largest overall score vector?

### Task 4 — Dot Product

Compare two students.

In [6]:
alice = X[0]
charlie = X[2]

similarity = np.dot(alice, charlie)

print(similarity)

22838


Question:

- Does a higher dot product suggest more similar score patterns?

Yes

### Task 5 — Matrix Transformation

Scale every score by 10%.

In [7]:
scaled = X * 1.10

print(scaled)

[[ 93.5  99.   85.8]
 [ 77.   71.5  88. ]
 [101.2  96.8 100.1]
 [ 66.   79.2  74.8]
 [104.5 103.4 105.6]]


Observe:

- Direction of each score pattern stays the same.
- Magnitude increases.

### Task 6 — Matrix Multiplication

Suppose each subject has a weight:

In [8]:
weights = np.array([
    [0.4],
    [0.35],
    [0.25]
])

final_score = X @ weights

print(final_score)

[[85.  ]
 [70.75]
 [90.35]
 [66.2 ]
 [94.9 ]]


Questions:

- Why does the multiplication work?
- What is the shape of the result?

This is exactly how weighted scoring systems are implemented.

### Task 7 — Eigenvalue Preview

In [9]:
cov_matrix = np.cov(X.T)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print(eigenvalues)
print(eigenvectors)

[451.1835127    4.45199733  48.66448996]
[[ 0.69917266  0.70753231  0.10274052]
 [ 0.54070827 -0.42926954 -0.72343778]
 [ 0.46775223 -0.56136057  0.68270211]]


Answer:

- How many eigenvalues are returned?
- Why might they be useful?