In [2]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])

In [3]:
arr[2]

np.int64(15)

In [4]:
arr[-1]

np.int64(25)

In [5]:
arr[0]

np.int64(5)

In [8]:
arr[3:]

array([20, 25])

In [9]:
arr[::-1]

array([25, 20, 15, 10,  5])

In [12]:
arr[1::2]

array([10, 20])

In [13]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [15]:
X[1,1]

np.int64(5)

In [16]:
X[1]

array([4, 5, 6])

In [19]:
X[:, 2]

array([3, 6, 9])

In [22]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
X[:2, 1:]

array([[2, 3],
       [5, 6]])

In [24]:
X = np.arange(100).reshape((20, 5))

print(X.shape)

(20, 5)


In [25]:
X_new = X[:10]
print(X_new.shape)

(10, 5)


In [27]:
X[:,:2].shape

(20, 2)

In [31]:
x = np.arange(20000).reshape((1000, 20))
print(x.shape)

(1000, 20)


In [33]:
x[:].shape

(1000, 20)

In [34]:
x[:, 5:10].shape

(1000, 5)

In [35]:
x_new = x[:, 5:10]

print(x_new.shape)

(1000, 5)
