# NumPy

In [3]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix.shape)

(2, 3)


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

10
30


In [2]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr + 10)
print(arr * 2)

[11 12 13]
[2 4 6]


1. Difference between list and NumPy array?
 - list is python's built in data type whereas arrays are the external data type created using numpy library and its fast comparitably, list data type because numpy is build on top of C language.

2. Create:
   - 1D array
   - 2D array

3. Find shape of:
   [
     [1, 2],
     [3, 4],
     [5, 6]
   ]

4. Multiply array by 5

In [4]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3,)
1
3
int64


In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])

print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(2, 3)
2
6
int64


In [6]:
print(a*5)

print(b*5)

[ 5 10 15]
[[ 5 10 15]
 [20 25 30]]


In [7]:
marks = np.array([80, 90, 70, 85])

print(marks.mean())
print(marks.sum())

81.25
325


In [8]:
# adding bonus marks

print(marks + 5)


[85 95 75 90]
