In [1]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [2]:
print(a + b)

[11 22 33]


In [3]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [4]:
X+10

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [5]:
X*2

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180]])

In [6]:
X + np.array([1, 2, 3])

array([[11, 22, 33],
       [41, 52, 63],
       [71, 82, 93]])

In [7]:
X + np.array([[1], [2], [3]])

array([[11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [8]:
X * np.array([2, 3, 4])

array([[ 20,  60, 120],
       [ 80, 150, 240],
       [140, 240, 360]])

In [9]:
# X.shape = (100, 4)
# weights.shape = (4,)

# X*weights = ?