# vectors and matrices

### 1. What is difference between scalar and vector?
- Scaler is a single number like; 1, 4, 5, 2 etc.
- Vector is a list of numbers like; [4, 2, 4, 5].

2. What is matrix shape of:
   [
     [1, 2, 3],
     [4, 5, 6]
   ]

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.3 MB 13.4 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.3 MB 18.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 20.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 18.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\Akaha Jha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

A = [[1, 2, 3],[4, 5, 6]]

A = np.array(A)

print(A.shape)

(2, 3)


Q: 3 Why are matrices important in AI?
- Without matrices, we wouldn't have the mathematical language to represent complex data, the algorithmic efficiency to train deep networks, or the ability to leverage powerful hardware like GPUs. They are the mathematical backbone of the AI revolution.

### 4. Create:
   - one vector
   - one 3×3 matrix

In [4]:
v = [1, 2, 3]

print(np.array(v))

[1 2 3]


In [5]:
A = [[1, 2, 3],[4, 5, 6]]

print(np.array(A))

[[1 2 3]
 [4 5 6]]
